mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from posts.views import PostIndexView

urlpatterns = [
    path('', PostIndexView.as_view()),
    path('admin/', admin.site.urls),
    path('posts/', include("posts.urls")),
    path('users/', include("users.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

posts/urls.py
# -*- encoding: utf-8 -*-
"""
@Author : rock
@Email  : gaoxiaolei@donews.com
@Time   : 2021/6/29 9:32:15
@Docs   : do something
"""
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.PostIndexView.as_view(), name='posts'),
    path('<int:pk>/', views.PostDetailView.as_view(), name='detail'),
    path('<int:pk>/edit', views.PostEditView.as_view(), name='edit'),
    path('<int:pk>/comments/', views.CommentsView.as_view(), name='comments'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('parts/', views.PartView.as_view(), name='parts'),
    path('self/', views.PostSelfView.as_view(), name='self-posts'),
    path('vote/<int:pk>/<int:up_id>/', views.vote, name='vote'),

    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

posts/models.py
import datetime

from django.contrib import admin
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone


class Examine(models.IntegerChoices):
    WAITING = 1
    PASS = 2
    REJECT = 3


class Part(models.Model):
    name = models.CharField(max_length=20, verbose_name='版块')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "版块"
        verbose_name_plural = "版块"


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name='标题', null=False)
    text = models.TextField(verbose_name='正文', null=False)
    part = models.ForeignKey(Part, on_delete=models.CASCADE, verbose_name='所属版块', null=False)
    agree_count = models.IntegerField(verbose_name='赞同量', default=0)
    disagree_count = models.IntegerField(verbose_name='反对量', default=0)
    views_count = models.IntegerField(verbose_name='浏览量', default=0)
    comments_count = models.IntegerField(verbose_name='评论数', default=0)
    pub_date = models.DateTimeField(verbose_name='发布日期', default=timezone.now)
    edit_date = models.DateTimeField(verbose_name='编辑日期', default=timezone.now)
    examine = models.IntegerField(verbose_name='审核状态', default=1, choices=Examine.choices)
    is_delete = models.BooleanField(verbose_name='被删除？', default=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='作者', null=False)

    def __str__(self):
        return self.title

    @admin.display(
        boolean=True,
        ordering='pub_date',
        description='最近发布?',
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    class Meta:
        verbose_name = "帖子"
        verbose_name_plural = "帖子"

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, verbose_name='帖子', null=False)
    text = models.CharField(max_length=200, verbose_name='内容', null=False)
    sub = models.ForeignKey('self', on_delete=models.CASCADE, verbose_name='子评论', null=True)
    agree = models.IntegerField(default=0, verbose_name='赞同')
    disagree = models.IntegerField(default=0, verbose_name='反对')
    examine = models.IntegerField(verbose_name='审核状态', default=1, choices=Examine.choices)
    is_delete = models.BooleanField(verbose_name='被删除？', default=False)
    pub_date = models.DateTimeField(verbose_name='发布日期', default=timezone.now)

    def __str__(self):
        return self.text

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = "评论"

posts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, F
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Post, Comment, Part, Examine


class PostIndexView(generic.ListView):
    template_name = 'posts/index.html'
    context_object_name = 'post_list'
    paginate_by = 10

    def get_queryset(self):
        """Return the last five published questions."""
        res = Post.objects.filter(
            pub_date__lte=timezone.now(),
            examine=Examine.PASS,
            is_delete=False,
        )
        part = self.request.GET.get("part", "")
        if part != "":
            res = res.filter(part=part)
        q = self.request.GET.get("q", "")
        if q != "":
            res = res.filter(title__contains=q)

        return res.order_by('-pub_date')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['part_list'] = Part.objects.all()
        extra_args = ""
        part = self.request.GET.get("part", 0)
        context['select_part'] = Part.objects.filter(pk=part).first()
        if part:
            extra_args += f"&part={part}"
        q = self.request.GET.get("q", "")
        if q != "":
            extra_args += f"&q={q}"
        context['extra_args'] = extra_args
        return context


class PostSelfView(LoginRequiredMixin, generic.ListView):
    template_name = 'posts/index.html'
    context_object_name = 'post_list'
    paginate_by = 10

    def get_queryset(self):
        """Return the last five published questions."""
        res = Post.objects.filter(
            pub_date__lte=timezone.now(),
            author=self.request.user,
            is_delete=False,
        )
        part = self.request.GET.get("part", "")
        if part != "":
            res = res.filter(part=part)
        q = self.request.GET.get("q", "")
        if q != "":
            res = res.filter(title__contains=q)
        return res.order_by('-edit_date')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['part_list'] = Part.objects.all()
        extra_args = ""
        part = self.request.GET.get("part", 0)
        context['select_part'] = Part.objects.filter(pk=part).first()
        if part:
            extra_args += f"&part={part}"
        q = self.request.GET.get("q", "")
        if q != "":
            extra_args += f"&q={q}"
        context['extra_args'] = extra_args
        context["title"] = "我的帖子"
        return context


class PostDetailView(generic.DetailView):
    model = Post
    template_name = 'posts/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Post.objects.filter(
            Q(
                pub_date__lte=timezone.now(),
                examine=Examine.PASS,
                is_delete=False, ) |
            Q(author=self.request.user, is_delete=False)
        )

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['part_list'] = Part.objects.all()
        return context


class PostEditView(LoginRequiredMixin, generic.UpdateView):
    model = Post
    template_name = 'posts/edit.html'
    fields = ['title', 'text']

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Post.objects.filter(
            pub_date__lte=timezone.now(),
            examine=Examine.PASS,
            is_delete=False,
            author=self.request.user,
        )

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['part_list'] = Part.objects.all()
    #     return context


class PostCreateView(LoginRequiredMixin, generic.CreateView):
    model = Post
    template_name = 'posts/edit.html'
    fields = ['part', 'title', 'text', ]
    success_url = '/posts/self/'

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


class CommentsView(LoginRequiredMixin, generic.DetailView):
    model = Comment

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Comment.objects.filter(
            pub_date__lte=timezone.now(),
            examine=Examine.PASS,
            is_delete=False,
        )


class PartView(LoginRequiredMixin, generic.ListView):
    def get_queryset(self):
        """Return the last five published questions."""
        return Part.objects.all()


@login_required()
def vote(request, pk, up_id):
    if up_id not in (1, 2):
        return HttpResponseBadRequest()
    question = get_object_or_404(Post, pk=pk)
    if up_id == 1:
        question.agree_count = F('agree_count') + 1
    if up_id == 2:
        question.disagree_count = F('disagree_count') + 1
    question.save()

    return HttpResponseRedirect(reverse("posts:posts"))

posts/templates/posts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{%  firstof title select_part.name '首页' %}{% endblock %}</title>
    {% block css %}
        {#        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">#}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="container">
    {% block nav %}
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'posts:posts' %}">Home</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            {% if select_part %}
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                   aria-haspopup="true"
                                   aria-expanded="false">{{ select_part.name | title }}<span class="caret"></span></a>
                            {% else %}
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                   aria-haspopup="true"
                                   aria-expanded="false">All<span class="caret"></span></a>
                            {% endif %}

                            <ul class="dropdown-menu">
                                {% for part in part_list %}
                                    <li {% if part.id == select_part.id %} class="active" {% endif %}><a
                                            href="?part={{ part.id }}">{{ part.name | title }}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                    <form class="navbar-form navbar-left">
                        <div class="form-group">
                            <input name="q" type="text" class="form-control" placeholder="Search">
                            {% if select_part %}
                                <input name="part" type="hidden" value="{{ select_part.id }}">
                            {% endif %}
                        </div>
                        <button type="submit" class="btn btn-default">Submit</button>
                    </form>
                    {% block user %}
                        <ul class="nav navbar-nav navbar-right">
                            {% if user.is_superuser %}
                                <li><a href="/admin/">后台管理</a></li>
                            {% endif %}
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                                   aria-haspopup="true"
                                   aria-expanded="false">{% firstof user.get_short_name user.get_username "游客" %}<span
                                        class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="{% url "posts:create" %}">新建帖子</a></li>
                                    <li><a href="{% url 'posts:self-posts' %}">我的帖子</a></li>
                                    {% if user.is_active %}
                                        <li><a href="{% url 'logout' %}">退出登录</a></li>
                                        {% else %}
                                        <li><a href="{% url 'login' %}">登录</a></li>
                                    {% endif %}
                                </ul>
                            </li>
                        </ul>
                    {% endblock %}

                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    {% endblock %}



    {% block content %}

    {% endblock %}
</div>

</body>
</html>

posts/templates/posts/detail.html
{% extends "posts/base.html" %}
{% load static %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'editormd/css/editormd.preview.css' %}"/>

{% endblock %}

{% block js %}
    {{ block.super }}
    <script src="{% static 'editormd/editormd.js' %}"></script>
    <script src="{% static 'editormd/lib/marked.min.js' %}"></script>
    <script src="{% static 'editormd/lib/prettify.min.js' %}"></script>
    <script type="text/javascript">
        $(function () {
            var testView = editormd.markdownToHTML("test-markdown-view", {
                {#markdown : "[TOC]\n### Hello world!\n## Heading 2", // Also, you can dynamic set Markdown text#}
                {#htmlDecode : true,  // Enable / disable HTML tag encode.#}
                {#htmlDecode : "style,script,iframe",  // Note: If enabled, you should filter some dangerous HTML tags for website security.#}
            });
        });
    </script>
{% endblock %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block nav %}
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'posts:posts' %}">Home</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                {% block user %}
                    {{ block.super }}
                {% endblock %}
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>

{% endblock %}

{% block content %}
    <div id="test-markdown-view">
        <!-- Server-side output Markdown text -->
        <textarea style="display:none;">
## {{ post.title }}

{{ post.text }}
        </textarea>
    </div>

    {% if post.author == user %}
        <a class="btn btn-default" href="{% url 'posts:edit' post.pk %}">编辑</a>
    {% endif %}

    <a class="btn btn-default" onclick="window.history.back()">返回</a>

{% endblock %}

posts/templates/posts/edit.html
{% extends "posts/detail.html" %}
{% load static %}

{% block title %}
    新建/编辑
{% endblock %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'editormd/css/editormd.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'posts/edit.css' %}"/>
{% endblock %}
{% block js %}
    {{ block.super }}
    <script src="{% static 'editormd/editormd.min.js' %}"></script>
    <script type="text/javascript">

        $(function () {
            $("#id_title").addClass("form-control");
            $("#id_text").wrap("<div id='editor'></div>").parent();
            $("#id_part").addClass("form-control");
            var editor = editormd("editor", {
                {#width: "100%",#}
                height: "400px",
                {#markdown: "xxxx",     // dynamic set Markdown text#}
                path: "{% static 'editormd/lib/' %}"  // Autoload modules mode, codemirror, marked... dependents libs path
            });
        });
    </script>
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-default" type="submit" value="保存">
        <a class="btn btn-default" onclick="window.history.back()">返回</a>
    </form>
{% endblock %}

posts/templates/posts/index.html
{% extends "posts/base.html" %}
{% load static %}

{#{% block css %}#}
{#    {{ block.super }}#}
{#    <link rel="stylesheet" type="text/css" href="{% static 'posts/style.css' %}">#}
{#{% endblock %}#}

{% block content %}
    <ul class="list-group">
        {% for post in post_list %}
            <li class="list-group-item">
                <div class="media" style="display: flex">
                    <div class="media-body">
                        {{ post.author }}
                        <a
                                href="{% url 'posts:detail' post.pk %}">{{ post.title }}
                            {% if post.was_published_recently %}
                                <i style="font-size: .9em;color: #dd4848;margin-left: 5px;"
                                   title="一天内发布的文章">new</i>{% endif %}
                        </a>
                        {% if request.path == "/posts/self/" %}
                            {% if post.examine == 1 %}
                                <span class="label label-warning">待审核</span>
                            {% endif %}
                        {% endif %}
                        <span style="float: right;text-align:center;">
                    <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                               class="bi bi-clock" viewBox="0 0 16 16">
  <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/>
  <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z"/>
</svg>
                        {{ post.pub_date | date:"Y/m/d H:i:s" }}</span> |
        <span> <a href="{% url "posts:vote" post.id 1 %}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                                               fill="currentColor" class="bi bi-hand-thumbs-up"
                                                               viewBox="0 0 16 16">
  <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
</svg></a> {{ post.agree_count }} </span> | <span><a href="{% url "posts:vote" post.id 2 %}"><svg
                                xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                fill="currentColor" class="bi bi-hand-thumbs-down"
                                viewBox="0 0 16 16">
  <path d="M8.864 15.674c-.956.24-1.843-.484-1.908-1.42-.072-1.05-.23-2.015-.428-2.59-.125-.36-.479-1.012-1.04-1.638-.557-.624-1.282-1.179-2.131-1.41C2.685 8.432 2 7.85 2 7V3c0-.845.682-1.464 1.448-1.546 1.07-.113 1.564-.415 2.068-.723l.048-.029c.272-.166.578-.349.97-.484C6.931.08 7.395 0 8 0h3.5c.937 0 1.599.478 1.934 1.064.164.287.254.607.254.913 0 .152-.023.312-.077.464.201.262.38.577.488.9.11.33.172.762.004 1.15.069.13.12.268.159.403.077.27.113.567.113.856 0 .289-.036.586-.113.856-.035.12-.08.244-.138.363.394.571.418 1.2.234 1.733-.206.592-.682 1.1-1.2 1.272-.847.283-1.803.276-2.516.211a9.877 9.877 0 0 1-.443-.05 9.364 9.364 0 0 1-.062 4.51c-.138.508-.55.848-1.012.964l-.261.065zM11.5 1H8c-.51 0-.863.068-1.14.163-.281.097-.506.229-.776.393l-.04.025c-.555.338-1.198.73-2.49.868-.333.035-.554.29-.554.55V7c0 .255.226.543.62.65 1.095.3 1.977.997 2.614 1.709.635.71 1.064 1.475 1.238 1.977.243.7.407 1.768.482 2.85.025.362.36.595.667.518l.262-.065c.16-.04.258-.144.288-.255a8.34 8.34 0 0 0-.145-4.726.5.5 0 0 1 .595-.643h.003l.014.004.058.013a8.912 8.912 0 0 0 1.036.157c.663.06 1.457.054 2.11-.163.175-.059.45-.301.57-.651.107-.308.087-.67-.266-1.021L12.793 7l.353-.354c.043-.042.105-.14.154-.315.048-.167.075-.37.075-.581 0-.211-.027-.414-.075-.581-.05-.174-.111-.273-.154-.315l-.353-.354.353-.354c.047-.047.109-.176.005-.488a2.224 2.224 0 0 0-.505-.804l-.353-.354.353-.354c.006-.005.041-.05.041-.17a.866.866 0 0 0-.121-.415C12.4 1.272 12.063 1 11.5 1z"/>
</svg></a>
                            {{ post.disagree_count }}</span>

</span>


                        {#                <p>{{ post.text|striptags|truncatechars:120 }}</p>#}

                    </div>
                </div>
            </li>
        {% empty %}
                <h3>暂无博客，敬请期待</h3>
        {% endfor %}
    </ul>
    {% if page_obj.paginator.count > 0 %}
        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if page_obj.number == 1 %}
                    <li class="disabled">
                        <a href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li>
                        <a href="?page=1{{ extra_args }}" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}
                {% if page_obj.has_previous %}
                    <li>
                        <a href="?page={{ page_obj.previous_page_number }}{{ extra_args }}">上一页</a>
                    </li>
                {% else %}
                    <li class="disabled">
                        <a href="#">上一页</a>
                    </li>
                {% endif %}

                {% for i in page_obj.paginator.page_range %}
                    {% if i == page_obj.number %}
                        <li class="active"><a href="?page={{ i }}{{ extra_args }}">{{ i }}</a></li>
                    {% else %}
                        <li><a href="?page={{ i }}{{ extra_args }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <li>
                        <a href="?page={{ page_obj.next_page_number }}{{ extra_args }}">下一页</a>
                    </li>
                {% else %}
                    <li class="disabled">
                        <a href="#">下一页</a>
                    </li>
                {% endif %}

                {% if page_obj.number < page_obj.paginator.num_pages %}
                    <li>
                        <a href="?page={{ page_obj.paginator.num_pages }}{{ extra_args }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% else %}
                    <li class="disabled">
                        <a href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}
{% endblock %}